steps:
  - label: ":golangci-lint: lint :lint-roller:"
    key: "lint"
    plugins:
      - docker#v5.7.0:
          image: "registry.hub.docker.com/golangci/golangci-lint:v1.43-alpine"
          command: ["golangci-lint", "run", "-v"]

  - label: ":test_tube: test"
    key: "test"
    plugins:
      - docker#v5.7.0:
          image: "golang:1.20"
          command: ["go", "test", "-cover" ,"-race", "./..."]
